UI.Dialog=function(c){p.call(this,c);this._body=UI.DC("div");this._body.className="dialog2";this._body.innerHTML=(UI.Browser.ie6?'<iframe src="javascript:false;" class="cover_select"></iframe>':"")+'<div class="bg"></div><div style="margin:-'+c.height/2+"px 0 0 -"+c.width/2+"px;width:"+c.width+"px;height:"+c.height+'px;" class="wrap"><div class="title">'+c.title+'</div><a class="close '+(c.close!=false?"":"hide")+'" href="javascript:void '+c.name+'.hide();" onfocus="this.blur();" title="Close" tabindex="-1"></a><div class="cont"><div class="loading"><span>loading...</span></div><iframe allowtransparency="true" src="'+
c.url+'" style="height:'+c.height+'px;display:none;" scrolling="auto" frameborder="no" onload="var Self = '+c.name+" || top."+c.name+";if (UI.A(this,'src') != 'undefined') { this.style.display='block';this.previousSibling.style.display='none';UI.EA("+c.name+'._iframe.contentWindow.document,\'keyup\',Self.key); }" class="iframe"></iframe><div class="data"></div></div><b class="cor_1"></b><b class="cor_2"></b><b class="cor_3"></b><b class="cor_4"></b><div class="resize"></div></div><div class="border"></div>';
this._bg=UI.GC(this._body,"div.bg")[0];this._wrap=UI.GC(this._body,"div.wrap")[0];this._title=UI.GC(this._body,"div.title")[0];this._close=UI.GC(this._body,"a.close")[0];this._cont=UI.GC(this._body,"div.cont")[0];this._iframe=UI.GC(this._body,"iframe.iframe")[0];this._data=UI.GC(this._body,"div.data")[0];this._resize=UI.GC(this._body,"div.resize")[0];this._border=UI.GC(this._body,"div.border")[0];this._loading=UI.GC(this._body,"div.loading")[0];this.checkStaus=function(a){if(!this._titleHeight){this._titleHeight=
this._title.offsetHeight;if(UI.Browser.ie&&document.compatMode=="CSS1Compat"){var b=parseInt(UI.C(this._title,"paddingTop"))+parseInt(UI.C(this._title,"paddingBottom"));this._titleHeight-=b;this._title.style.height=this._titleHeight-b+"px"}}try{this._cont.style.height=this._iframe.style.height=a.height-this._titleHeight+"px"}catch(e){}if(a.move==false){this.__move=false;this._title.style.cursor="default"}else if(this.__move==undefined||a.move){this.__move=true;this._title.style.cursor=""}if(a.resize==
false){this.__resize=false;this._resize.style.display="none"}else if(this.__resize==undefined||a.resize){this.__resize=true;this._resize.style.display=""}a.html&&UI.hide(this._loading)};this.__name=c.name;this._cache=[];this._append=false;this.autoHeightMax=420;this.__close=c.close==undefined?true:c.close;var d=this;c.url&&UI.EA(window,"load",function(){document.body.appendChild(d._body);d._append=true;d.__display=true;d.checkStaus.call(d,c);d._cache.push(c)});var f=this._wrap,h=this._border,g=c.name;
this.key=function(a){switch(UI.E(a).key){case 27:window[g].__display&&window[g].hide();break}};this.resizeBg=function(){if(d.__display){if(UI.Browser.ie)d._bg.style.cssText+=";width:100%;";d._body.style.height=UI.windowHeight();d.delay=setTimeout(function(){var a=UI.pageHeight(),b=UI.windowHeight();d._bg.style.cssText+=";width:"+UI.pageWidth()+"px;height:"+(a<b?b:a)+"px;"},0)}};UI.EA(document,"keyup",this.key);UI.EA(window,"resize",this.resizeBg);this._title.onmousedown=function(a){if(window[g].__move){a=
window.event||a;var b=a.clientX-parseInt(f.style.marginLeft),e=a.clientY-parseInt(f.style.marginTop),i=UI.windowWidth(),l=UI.windowHeight();a.preventDefault&&a.preventDefault();UI.addClass(f,"move");document.onmousemove=function(j){var m=window.event||j;j=UI.E(j);if(!UI.Browser.ie&&(j.x<0||j.y<0||j.x>i||j.y>l))return false;f.style.marginTop=m.clientY-e+"px";f.style.marginLeft=m.clientX-b+"px";return false};document.onmouseup=function(){this.onmousemove=null;document.onmouseup=null;UI.removeClass(f,
"move")};return false}};this._title.ondblclick=function(){var a=window[g]._cache[window[g]._cache.length-1];window[g].reset(a)};this._resize.onmousedown=function(a){if(window[g].__resize){var b=parseInt(UI.C(f,"width")),e=parseInt(UI.C(f,"height")),i=parseInt(UI.getY(f)),l=parseInt(UI.getX(f));if(!UI.Browser.ie||document.compatMode=="CSS1Compat"){b-=2;e-=2}h.style.cssText="top:"+i+"px;left:"+l+"px;width:"+b+"px;height:"+e+"px;display:block;";window[g]._body.style.cursor="se-resize";a=window.event||
a;var j=a.clientX,m=a.clientY;a.preventDefault&&a.preventDefault();UI.addClass(f,"move");document.onmousemove=function(k){k=window.event||k;var n=k.clientY-m,o=k.clientX-j;k=(150-b)/2;var q=(100-e)/2;if(n<q)n=q;if(o<k)o=k;var r="height:"+(n*2+e)+"px;width:"+(o*2+b)+"px;top:"+(i-n)+"px;left:"+(l-o)+"px;display:block;";if(UI.Browser.ie6&&document.compatMode=="BackCompat")setTimeout(function(){h.style.cssText=r},10);else h.style.cssText=r;return false};document.onmouseup=function(){window[g]._wrap.style.cssText=
"margin:0;left:"+h.style.left+";top:"+h.style.top+";width:"+h.offsetWidth+"px;height:"+h.offsetHeight+"px;";window[g].checkStaus({height:h.offsetHeight});setTimeout(function(){h.style.display="none"},15);window[g]._body.style.cursor="";this.onmousemove=null;document.onmouseup=null;UI.removeClass(f,"move")};return false}};this._cont.onclick=function(){if(d.autoHeight){clearTimeout(d.delay);d.delay=setTimeout(function(){if(!d.__display)return false;d.height()},100)}};this.hide=function(){var a=UI.Dialog.cache;
if(!this.__close||a[a.length-1]!=this.__name&&a.length>0)return false;var b=this._cache.length;if(b>1){this.reset(this._cache[b-2]);this._cache[b-1].call&&eval(this._cache[b-1].call)}else if(b==0){UI.hide(this._body);return this.__display=false}else{UI.hide(this._body);if((b=this._cache[0].html)&&!UI.isString(b)){document.body.appendChild(b);UI.hide(b)}this._cache[0].call&&eval(this._cache[0].call);this.__display=false}this.__title=this._cache[0].title;this._cache.pop();if(this._cache.length<1&&a[a.length-
1]==this.__name){a.pop();a.length>0&&UI.show(window[a[a.length-1]]._bg)}this.title()};this.show=function(a){if(!this._append){document.body.appendChild(this._body);this._append=true}if(!this.__display){UI.show(this._body);this.__display=true}if(a){this.autoHeight=a.autoHeight||false;if(a.autoHeightMax)this.autoHeightMax=a.autoHeightMax;if(a.url||a.html){this._cache.push(a);var b=UI.Dialog.cache;if(b[b.length-1]!=this.__name){b.push(this.__name);for(var e=0,i=b.length-1;e<i;e++)UI.hide(window[b[e]]._bg)}this._cont.style.overflow=
a.url?"hidden":"auto"}else if(a.title)this._cache[this._cache.length-1].title=a.title;this.reset(a)}else this.reset({})};this.reset=function(a){a.title&&this.title();a.size&&p.call(this,a);var b=!!(a.html&&!UI.isString(a.html)&&!a.height);this._wrap.style.top="50%";this._wrap.style.left="50%";this._wrap.style.margin=-parseInt(UI.C(this._wrap,"height"))/2+UI.scrollY()+"px 0 0 "+(-parseInt(UI.C(this._wrap,"width"))/2+UI.scrollX())+"px";var e=UI.pageHeight(),i=UI.windowHeight();this._bg.style.cssText=
"width:"+UI.pageWidth()+"px;height:"+(e<i?i:e)+"px;";this._body.style.height=UI.windowHeight();if(a.width){if(a.width%2)a.width+=1;this._wrap.style.width=a.width+"px";this._wrap.style.marginLeft=-a.width/2+UI.scrollX()+"px"}if(a.height){if(a.height%2)a.height+=1;this._wrap.style.height=a.height+"px";this._wrap.style.marginTop=-a.height/2+UI.scrollY()+"px"}if(a.close)this._close.className="close"+(a.close!=false?"":"hide");if(a.url){UI.hide(this._iframe);UI.show(this._loading);this._iframe.setAttribute("src",
a.url)}else if(a.html){UI.hide(this._iframe);if(UI.isString(a.html)){UI.hide(this._loading);this._data.innerHTML=a.html}else{this._data.appendChild(a.html);UI.show(a.html)}}this.checkStaus.call(this,a);b&&this.height()};this.title=function(){for(var a=[],b=0;b<this._cache.length;b++)this._cache[b].title&&a.push(this._cache[b].title);a.length==0&&a.push(this.__title);this._title.innerHTML="<span>"+a.join('<b class="dot"></b>')+"</span>"};this.height=function(){var a=UI.height(this._data)+this._titleHeight;
this.show({autoHeight:this.autoHeight,height:a>this.autoHeightMax?this.autoHeightMax:a})};function p(a){switch(a.size){case "small":if(!a.width)a.width=380;if(!a.height)a.height=220;break;case "medium":if(!a.width)a.width=530;if(!a.height)a.height=420;break;case "big":if(!a.width)a.width=760;if(!a.height)a.height=540;break}}};UI.Dialog.cache=[];UI.Dialog.location=null;
